{
  "Data":{
    "train_set":"train_class",
    "test_set": "test_class",
    "train_percent": 1.0
  } ,
  "LSTM": {
    "batch_size": 10,
    "lr": 0.001,
    "num_of_epochs":2
  },
  "MLP": {
    "batch_size": 500,
    "lr": 0.001,
    "num_of_epochs":1,
    "input_size":54,
    "hidden_size":100,
    "target_idx":80,
    "wegihts": [0.98, 0.95, 1.04]
  }
}
